### ISSUE TITLE
para revisar

### ISSUE THREAD

**Issue by RodriFid** [CaC-Fullstack-NodeJS/Hood_Barber#27]
orden del navbar: no es el mismo en todas las paginas
telefono de arriba, sobre la barra negra: hay una segunda linea
logo para el footer: pase el grupo de Whatsapp un logo como desarrolladores

**Comment by RodriFid** [comment]
tengo problemas para validar el formulario de contacto en JS
sigo las instrucciones de la clase pero no me genera el alert

**Comment by MariaVictoria** [comment]
ok. gracias por avisar
